STORAGE_PLOTS_DOC = """
Plot selected hydrogen storage model results.

The function allows users to select one or more variables from the
``storage_results`` dictionary and generate individual time-series
plots for each selected variable.

Plot titles, axis labels, filenames, and general figure formatting
can be customised for each plot.

Parameters
----------
storage_results : dict
    Dictionary containing the results generated by the hydrogen
    storage model.

    Each key represents a storage result variable and its associated
    value should contain the data to be plotted.

    ===================================================
    NOTE: Check Storage class documentation for full list.
    ===================================================

    Example::

        storage_results = {
            "storage_level_kg": [...],
            "starting_storage_t": [...],
            "ending_storage_t": [...],
            "storage_charge_kgph": [...],
            "storage_discharge_kgph": [...]
        }

plots : list of dict
    List defining the storage results to plot.

    Each dictionary must contain a ``"key"`` corresponding to a key
    in ``storage_results``.

    Optional parameters for each plot are:

    ``"title"``
        Title of the plot.

    ``"xlabel"``
        Label for the x-axis.

    ``"ylabel"``
        Label for the y-axis.

    ``"filename"``
        Filename to use when saving the plot.

    Example::

        plots = [
            {
                "key": "storage_level_kg",
                "title": "Hydrogen Storage Level",
                "xlabel": "Hour",
                "ylabel": "Storage Level (kg)",
                "filename": "storage_level.png"
            },
            {
                "key": "storage_charge_kgph",
                "title": "Hydrogen Storage Charging",
                "xlabel": "Hour",
                "ylabel": "Charging Rate (kg/h)",
                "filename": "storage_charge.png"
            }
        ]

figsize : tuple, optional
    Figure size used for each plot, specified as
    ``(width, height)`` in inches.

    Default is ``(15, 5)``.

title_fontsize : int, optional
    Font size used for plot titles.

    Default is ``16``.

axis_fontsize : int, optional
    Font size used for x-axis and y-axis labels.

    Default is ``13``.

tick_fontsize : int, optional
    Font size used for axis tick labels.

    Default is ``11``.

linewidth : float, optional
    Width of the plotted lines.

    Default is ``1.5``.

grid : bool, optional
    Determines whether a grid is displayed on the plots.

    ``True``  = display the grid.
    ``False`` = do not display the grid.

    Default is ``True``.

save_plot : bool, optional
    Determines whether the generated plots are saved to files.

    ``True``  = save each plot.
    ``False`` = display the plots without saving them.

    Default is ``False``.

plot_file_prefix : str, optional
    Directory in which plots are saved when ``save_plot=True``.

    The directory is created automatically if it does not already
    exist.

    Default is ``"plots/storage"``.

Raises
------
ValueError
    If ``plots`` is not a non-empty list.

KeyError
    If a plot definition does not contain the required ``"key"``.

KeyError
    If a specified key is not found in ``storage_results``.

Notes
-----
Each selected storage result is plotted as an individual time-series
figure.

If a title, axis label, or filename is not specified for an individual
plot, a default value is generated from the corresponding result key.

For example, the key::

    "storage_level_kg"

is automatically converted to a default title or y-axis label of::

    "Storage Level Kg"

When ``save_plot=True``, plots are saved as PNG files at the specified
location.

Examples
--------
Plot a single storage variable::

    storage_plots(
        storage_results=storage_results,
        plots=[
            {
                "key": "storage_level_kg",
                "title": "Hydrogen Storage Level",
                "ylabel": "Storage Level (kg)"
            }
        ]
    )

Plot multiple storage variables::

    storage_plots(
        storage_results=storage_results,
        plots=[
            {
                "key": "storage_level_kg",
                "title": "Hydrogen Storage Level",
                "ylabel": "Storage Level (kg)"
            },
            {
                "key": "storage_charge_kgph",
                "title": "Storage Charging Rate",
                "ylabel": "Charging Rate (kg/h)"
            },
            {
                "key": "storage_discharge_kgph",
                "title": "Storage Discharging Rate",
                "ylabel": "Discharging Rate (kg/h)"
            }
        ]
    )

Save plots to a folder::

    storage_plots(
        storage_results=storage_results,
        plots=[
            {
                "key": "storage_level_kg",
                "title": "Hydrogen Storage Level",
                "ylabel": "Storage Level (kg)",
                "filename": "storage_level.png"
            }
        ],
        save_plot=True,
        plot_file_prefix="results/storage"
    )

Display plots without saving them::

    storage_plots(
        storage_results=storage_results,
        plots=plots,
        save_plot=False,
        show_plot=True
    )
"""