[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hytea"
version = "0.9.1.2"
description = "Hydrogen supply chain techno-economic analysis library"
authors = [
    { name="Haresh", email="hareshmvc@gmail.com" }
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "pyyaml"  
]